# Generated by Django 4.2.1 on 2024-04-10 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gcna_data', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='in_house_drying',
            name='entryCheck',
        ),
        migrations.AlterField(
            model_name='shelves',
            name='entry',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
