# Generated by Django 4.2.1 on 2024-04-10 18:39

from django.db import migrations, models
import gcna_data.models


class Migration(migrations.Migration):

    dependencies = [
        ('gcna_data', '0002_remove_in_house_drying_entrycheck_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='in_house_drying',
            name='entryCheck',
            field=models.CharField(default=gcna_data.models.shelf_id, max_length=50),
        ),
    ]
