# Generated by Django 4.2.1 on 2024-04-15 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gcna_data', '0003_in_house_drying_entrycheck'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispatch_of_dried_nutmeg',
            name='Worker_ID_No',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='dispatch_of_dried_nutmeg',
            name='Worker_Name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='dispatch_of_green_nutmeg',
            name='Worker_ID_No',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='dispatch_of_green_nutmeg',
            name='Worker_Name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='dried_moisture_analysis_a',
            name='Worker_ID_No',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='dried_moisture_analysis_a',
            name='Worker_Name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='floated_moisture_analysis_a',
            name='Worker_ID_No',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='floated_moisture_analysis_a',
            name='Worker_Name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='floation_summary',
            name='Worker_ID_No',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='floation_summary',
            name='Worker_Name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='in_house_drying',
            name='Worker_ID_No',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='in_house_drying',
            name='Worker_Name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='package_ciontrol',
            name='Worker_ID_No',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='package_ciontrol',
            name='Worker_Name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='quality_control',
            name='Worker_ID_No',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='quality_control',
            name='Worker_Name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sanitation_a',
            name='Worker_ID_No',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sanitation_a',
            name='Worker_Name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sanitation_b',
            name='Worker_ID_No',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sanitation_b',
            name='Worker_Name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sanitation_c',
            name='Worker_ID_No',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sanitation_c',
            name='Worker_Name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='in_house_drying',
            name='PLACE_OF_PURCHASE',
            field=models.CharField(choices=[('', '--Select Location--'), ('G', 'Grenville'), ('H', 'Hermitage'), ('M', 'Marli'), ('U', 'Union'), ('GP', 'Gouyave')], max_length=50, null=True, verbose_name='Place of Purchase '),
        ),
    ]
