# Generated by Django 4.2.1 on 2024-04-15 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gcna_data', '0004_dispatch_of_dried_nutmeg_worker_id_no_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dispatch_of_dried_nutmeg',
            old_name='Worker_Name',
            new_name='Worker_ID_Name',
        ),
        migrations.RenameField(
            model_name='dispatch_of_green_nutmeg',
            old_name='Worker_Name',
            new_name='Worker_ID_Name',
        ),
        migrations.RenameField(
            model_name='dried_moisture_analysis_a',
            old_name='Worker_Name',
            new_name='Worker_ID_Name',
        ),
        migrations.RenameField(
            model_name='floated_moisture_analysis_a',
            old_name='Worker_Name',
            new_name='Worker_ID_Name',
        ),
        migrations.RenameField(
            model_name='floation_summary',
            old_name='Worker_Name',
            new_name='Worker_ID_Name',
        ),
        migrations.RenameField(
            model_name='in_house_drying',
            old_name='Worker_Name',
            new_name='Worker_ID_Name',
        ),
        migrations.RenameField(
            model_name='package_ciontrol',
            old_name='Worker_Name',
            new_name='Worker_ID_Name',
        ),
        migrations.RenameField(
            model_name='quality_control',
            old_name='Worker_Name',
            new_name='Worker_ID_Name',
        ),
        migrations.RenameField(
            model_name='sanitation_a',
            old_name='Worker_Name',
            new_name='Worker_ID_Name',
        ),
        migrations.RenameField(
            model_name='sanitation_b',
            old_name='Worker_Name',
            new_name='Worker_ID_Name',
        ),
        migrations.RenameField(
            model_name='sanitation_c',
            old_name='Worker_Name',
            new_name='Worker_ID_Name',
        ),
        migrations.AddField(
            model_name='cracking_schedule',
            name='Worker_ID_Name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='cracking_schedule',
            name='Worker_ID_No',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
