# Generated by Django 4.2.1 on 2024-04-17 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gcna_data', '0005_rename_worker_name_dispatch_of_dried_nutmeg_worker_id_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cracking_schedule',
            name='Worker_ID_Name',
        ),
        migrations.RemoveField(
            model_name='cracking_schedule',
            name='Worker_ID_No',
        ),
        migrations.AddField(
            model_name='cracking_summary',
            name='Worker_ID_Name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='cracking_summary',
            name='Worker_ID_No',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
