# Generated by Django 4.2.1 on 2024-04-24 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gcna_data', '0006_remove_cracking_schedule_worker_id_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cracking_summary',
            name='Date_Created',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Date Created'),
        ),
        migrations.AlterField(
            model_name='dispatch_of_dried_nutmeg',
            name='Date_Created',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Date Created'),
        ),
        migrations.AlterField(
            model_name='dispatch_of_green_nutmeg',
            name='Date_Created',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Date Created'),
        ),
        migrations.AlterField(
            model_name='dried_moisture_analysis_a',
            name='Date_Created',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Date Created'),
        ),
        migrations.AlterField(
            model_name='dried_moisture_analysis_b',
            name='Date_Created',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Date Created'),
        ),
        migrations.AlterField(
            model_name='floated_moisture_analysis_a',
            name='Date_Created',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Date Created'),
        ),
        migrations.AlterField(
            model_name='floated_moisture_analysis_b',
            name='Date_Created',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Date Created'),
        ),
        migrations.AlterField(
            model_name='in_house_drying',
            name='Date_Created',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Date Created'),
        ),
        migrations.AlterField(
            model_name='package_ciontrol',
            name='Date_Created',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Date Created'),
        ),
        migrations.AlterField(
            model_name='quality_control',
            name='Date_Created',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Date Created'),
        ),
    ]
