# Generated by Django 4.2.1 on 2024-05-02 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gcna_data', '0007_alter_cracking_summary_date_created_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='M_Shelves',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry', models.CharField(blank=True, max_length=50, null=True)),
                ('floor', models.CharField(blank=True, max_length=50, null=True)),
                ('station', models.CharField(blank=True, max_length=50, null=True)),
                ('M_Shelf', models.CharField(blank=True, max_length=50, null=True)),
                ('M_Tray', models.CharField(blank=True, max_length=50, null=True)),
                ('M_Section', models.CharField(blank=True, max_length=50, null=True)),
                ('Moisture', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='W_Shelves',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry', models.CharField(blank=True, max_length=50, null=True)),
                ('floor', models.CharField(blank=True, max_length=50, null=True)),
                ('station', models.CharField(blank=True, max_length=50, null=True)),
                ('W_Shelf', models.CharField(blank=True, max_length=50, null=True)),
                ('W_Tray', models.CharField(blank=True, max_length=50, null=True)),
                ('W_Section', models.CharField(blank=True, max_length=50, null=True)),
                ('Moisture', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='cracking_summary',
            name='Date_Created',
        ),
        migrations.RemoveField(
            model_name='dispatch_of_dried_nutmeg',
            name='Date_Created',
        ),
        migrations.RemoveField(
            model_name='dispatch_of_green_nutmeg',
            name='Date_Created',
        ),
        migrations.RemoveField(
            model_name='dried_moisture_analysis_a',
            name='Date_Created',
        ),
        migrations.RemoveField(
            model_name='dried_moisture_analysis_b',
            name='Date_Created',
        ),
        migrations.RemoveField(
            model_name='floated_moisture_analysis_a',
            name='Date_Created',
        ),
        migrations.RemoveField(
            model_name='floated_moisture_analysis_b',
            name='Date_Created',
        ),
        migrations.RemoveField(
            model_name='in_house_drying',
            name='Date_Created',
        ),
        migrations.RemoveField(
            model_name='package_ciontrol',
            name='Date_Created',
        ),
        migrations.RemoveField(
            model_name='quality_control',
            name='Date_Created',
        ),
        migrations.AlterField(
            model_name='in_house_drying',
            name='END_DRYING_DATE',
            field=models.DateField(blank=True, null=True, verbose_name='End drying date'),
        ),
        migrations.AddField(
            model_name='cracking_summary',
            name='DATE_CREATED',
            field=models.DateField(null=True, verbose_name='Date of Sampling'),
        ),
        migrations.AddField(
            model_name='dispatch_of_dried_nutmeg',
            name='DATE_CREATED',
            field=models.DateField(null=True, verbose_name='Date of Sampling'),
        ),
        migrations.AddField(
            model_name='dispatch_of_green_nutmeg',
            name='DATE_CREATED',
            field=models.DateField(null=True, verbose_name='Date of Sampling'),
        ),
        migrations.AddField(
            model_name='dried_moisture_analysis_a',
            name='DATE_CREATED',
            field=models.DateField(null=True, verbose_name='Date of Sampling'),
        ),
        migrations.AddField(
            model_name='dried_moisture_analysis_b',
            name='DATE_CREATED',
            field=models.DateField(null=True, verbose_name='Date of Sampling'),
        ),
        migrations.AddField(
            model_name='floated_moisture_analysis_a',
            name='DATE_CREATED',
            field=models.DateField(null=True, verbose_name='Date of Sampling'),
        ),
        migrations.AddField(
            model_name='floated_moisture_analysis_b',
            name='DATE_CREATED',
            field=models.DateField(null=True, verbose_name='Date of Sampling'),
        ),
        migrations.AddField(
            model_name='in_house_drying',
            name='DATE_CREATED',
            field=models.DateField(null=True, verbose_name='Date of Sampling'),
        ),
        migrations.AddField(
            model_name='package_ciontrol',
            name='DATE_CREATED',
            field=models.DateField(null=True, verbose_name='Date of Sampling'),
        ),
        migrations.AddField(
            model_name='quality_control',
            name='DATE_CREATED',
            field=models.DateField(null=True, verbose_name='Date of Sampling'),
        ),
    ]
