# Generated by Django 4.2.1 on 2024-05-05 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gcna_data', '0008_m_shelves_w_shelves_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='M_Shelves_Dried',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry', models.CharField(blank=True, max_length=50, null=True)),
                ('floor', models.CharField(blank=True, max_length=50, null=True)),
                ('station', models.CharField(blank=True, max_length=50, null=True)),
                ('M_Shelf', models.CharField(blank=True, max_length=50, null=True)),
                ('M_Tray', models.CharField(blank=True, max_length=50, null=True)),
                ('M_Section', models.CharField(blank=True, max_length=50, null=True)),
                ('Moisture', models.CharField(blank=True, max_length=50, null=True)),
                ('labelText', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='W_Shelves_Dried',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry', models.CharField(blank=True, max_length=50, null=True)),
                ('floor', models.CharField(blank=True, max_length=50, null=True)),
                ('station', models.CharField(blank=True, max_length=50, null=True)),
                ('W_Shelf', models.CharField(blank=True, max_length=50, null=True)),
                ('W_Tray', models.CharField(blank=True, max_length=50, null=True)),
                ('W_Section', models.CharField(blank=True, max_length=50, null=True)),
                ('Moisture', models.CharField(blank=True, max_length=50, null=True)),
                ('labelText', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='m_shelves',
            name='labelText',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='w_shelves',
            name='labelText',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='dispatch_of_dried_nutmeg',
            name='Section',
            field=models.CharField(blank=True, choices=[('', '--Select Section--'), ('1-3', '1-3'), ('4-6', '4-6'), ('7-9', '7-9')], max_length=50, null=True, verbose_name='Section'),
        ),
        migrations.AlterField(
            model_name='dispatch_of_dried_nutmeg',
            name='SectionG',
            field=models.CharField(blank=True, choices=[('', '--Select Section--'), ('1-3', '1-3'), ('4-6', '4-6'), ('7-9', '7-9')], max_length=50, null=True, verbose_name='Section'),
        ),
        migrations.AlterField(
            model_name='dispatch_of_dried_nutmeg',
            name='SectionGP_1F',
            field=models.CharField(blank=True, choices=[('', '--Select Section--'), ('1-3', '1-3'), ('4-6', '4-6'), ('7-9', '7-9')], max_length=50, null=True, verbose_name='Section'),
        ),
        migrations.AlterField(
            model_name='dispatch_of_dried_nutmeg',
            name='SectionGP_2F',
            field=models.CharField(blank=True, choices=[('', '--Select Section--'), ('1-3', '1-3'), ('4-6', '4-6'), ('7-9', '7-9')], max_length=50, null=True, verbose_name='Section'),
        ),
        migrations.AlterField(
            model_name='dispatch_of_dried_nutmeg',
            name='SectionGP_FL',
            field=models.CharField(blank=True, choices=[('', '--Select Section--'), ('1-3', '1-3'), ('4-6', '4-6'), ('7-9', '7-9')], max_length=50, null=True, verbose_name='Section'),
        ),
        migrations.AlterField(
            model_name='dispatch_of_dried_nutmeg',
            name='SectionGP_GF',
            field=models.CharField(blank=True, choices=[('', '--Select Section--'), ('1-3', '1-3'), ('4-6', '4-6'), ('7-9', '7-9')], max_length=50, null=True, verbose_name='Section'),
        ),
        migrations.AlterField(
            model_name='dispatch_of_dried_nutmeg',
            name='SectionG_1F',
            field=models.CharField(blank=True, choices=[('', '--Select Section--'), ('1-3', '1-3'), ('4-6', '4-6'), ('7-9', '7-9')], max_length=50, null=True, verbose_name='Section'),
        ),
        migrations.AlterField(
            model_name='dispatch_of_dried_nutmeg',
            name='SectionG_2F',
            field=models.CharField(blank=True, choices=[('', '--Select Section--'), ('1-3', '1-3'), ('4-6', '4-6'), ('7-9', '7-9')], max_length=50, null=True, verbose_name='Section'),
        ),
        migrations.AlterField(
            model_name='dispatch_of_dried_nutmeg',
            name='SectionG_FL',
            field=models.CharField(blank=True, choices=[('', '--Select Section--'), ('1-3', '1-3'), ('4-6', '4-6'), ('7-9', '7-9')], max_length=50, null=True, verbose_name='Section'),
        ),
        migrations.AlterField(
            model_name='dispatch_of_dried_nutmeg',
            name='SectionG_GF',
            field=models.CharField(blank=True, choices=[('', '--Select Section--'), ('1-3', '1-3'), ('4-6', '4-6'), ('7-9', '7-9')], max_length=50, null=True, verbose_name='Section'),
        ),
        migrations.AlterField(
            model_name='dispatch_of_dried_nutmeg',
            name='SectionH_1F',
            field=models.CharField(blank=True, choices=[('', '--Select Section--'), ('1-3', '1-3'), ('4-6', '4-6'), ('7-9', '7-9')], max_length=50, null=True, verbose_name='Section'),
        ),
        migrations.AlterField(
            model_name='dispatch_of_dried_nutmeg',
            name='SectionH_2F',
            field=models.CharField(blank=True, choices=[('', '--Select Section--'), ('1-3', '1-3'), ('4-6', '4-6'), ('7-9', '7-9')], max_length=50, null=True, verbose_name='Section'),
        ),
        migrations.AlterField(
            model_name='dispatch_of_dried_nutmeg',
            name='SectionH_FL',
            field=models.CharField(blank=True, choices=[('', '--Select Section--'), ('1-3', '1-3'), ('4-6', '4-6'), ('7-9', '7-9')], max_length=50, null=True, verbose_name='Section'),
        ),
        migrations.AlterField(
            model_name='dispatch_of_dried_nutmeg',
            name='SectionH_GF',
            field=models.CharField(blank=True, choices=[('', '--Select Section--'), ('1-3', '1-3'), ('4-6', '4-6'), ('7-9', '7-9')], max_length=50, null=True, verbose_name='Section'),
        ),
        migrations.AlterField(
            model_name='dispatch_of_dried_nutmeg',
            name='SectionM',
            field=models.CharField(blank=True, choices=[('', '--Select Section--'), ('1-3', '1-3'), ('4-6', '4-6'), ('7-9', '7-9')], max_length=50, null=True, verbose_name='Section'),
        ),
        migrations.AlterField(
            model_name='dispatch_of_dried_nutmeg',
            name='SectionM_1F',
            field=models.CharField(blank=True, choices=[('', '--Select Section--'), ('1-3', '1-3'), ('4-6', '4-6'), ('7-9', '7-9')], max_length=50, null=True, verbose_name='Section'),
        ),
        migrations.AlterField(
            model_name='dispatch_of_dried_nutmeg',
            name='SectionM_2F',
            field=models.CharField(blank=True, choices=[('', '--Select Section--'), ('1-3', '1-3'), ('4-6', '4-6'), ('7-9', '7-9')], max_length=50, null=True, verbose_name='Section'),
        ),
        migrations.AlterField(
            model_name='dispatch_of_dried_nutmeg',
            name='SectionM_FL',
            field=models.CharField(blank=True, choices=[('', '--Select Section--'), ('1-3', '1-3'), ('4-6', '4-6'), ('7-9', '7-9')], max_length=50, null=True, verbose_name='Section'),
        ),
        migrations.AlterField(
            model_name='dispatch_of_dried_nutmeg',
            name='SectionM_GF',
            field=models.CharField(blank=True, choices=[('', '--Select Section--'), ('1-3', '1-3'), ('4-6', '4-6'), ('7-9', '7-9')], max_length=50, null=True, verbose_name='Section'),
        ),
        migrations.AlterField(
            model_name='dispatch_of_dried_nutmeg',
            name='SectionU_1F',
            field=models.CharField(blank=True, choices=[('', '--Select Section--'), ('1-3', '1-3'), ('4-6', '4-6'), ('7-9', '7-9')], max_length=50, null=True, verbose_name='Section'),
        ),
        migrations.AlterField(
            model_name='dispatch_of_dried_nutmeg',
            name='SectionU_2F',
            field=models.CharField(blank=True, choices=[('', '--Select Section--'), ('1-3', '1-3'), ('4-6', '4-6'), ('7-9', '7-9')], max_length=50, null=True, verbose_name='Section'),
        ),
        migrations.AlterField(
            model_name='dispatch_of_dried_nutmeg',
            name='SectionU_FL',
            field=models.CharField(blank=True, choices=[('', '--Select Section--'), ('1-3', '1-3'), ('4-6', '4-6'), ('7-9', '7-9')], max_length=50, null=True, verbose_name='Section'),
        ),
        migrations.AlterField(
            model_name='dispatch_of_dried_nutmeg',
            name='SectionU_GF',
            field=models.CharField(blank=True, choices=[('', '--Select Section--'), ('1-3', '1-3'), ('4-6', '4-6'), ('7-9', '7-9')], max_length=50, null=True, verbose_name='Section'),
        ),
        migrations.AlterField(
            model_name='in_house_drying',
            name='Section',
            field=models.CharField(blank=True, choices=[('', '--Select Section--'), ('1-3', '1-3'), ('4-6', '4-6'), ('7-9', '7-9')], max_length=50, null=True, verbose_name='Section'),
        ),
        migrations.AlterField(
            model_name='in_house_drying',
            name='SectionG',
            field=models.CharField(blank=True, choices=[('', '--Select Section--'), ('1-3', '1-3'), ('4-6', '4-6'), ('7-9', '7-9')], max_length=50, null=True, verbose_name='Section'),
        ),
        migrations.AlterField(
            model_name='in_house_drying',
            name='SectionGP_0_1F',
            field=models.CharField(blank=True, choices=[('', '--Select Section--'), ('1-3', '1-3'), ('4-6', '4-6'), ('7-9', '7-9')], max_length=50, null=True, verbose_name='Section'),
        ),
        migrations.AlterField(
            model_name='in_house_drying',
            name='SectionGP_0_2F',
            field=models.CharField(blank=True, choices=[('', '--Select Section--'), ('1-3', '1-3'), ('4-6', '4-6'), ('7-9', '7-9')], max_length=50, null=True, verbose_name='Section'),
        ),
        migrations.AlterField(
            model_name='in_house_drying',
            name='SectionGP_0_FL',
            field=models.CharField(blank=True, choices=[('', '--Select Section--'), ('1-3', '1-3'), ('4-6', '4-6'), ('7-9', '7-9')], max_length=50, null=True, verbose_name='Section'),
        ),
        migrations.AlterField(
            model_name='in_house_drying',
            name='SectionGP_0_GF',
            field=models.CharField(blank=True, choices=[('', '--Select Section--'), ('1-3', '1-3'), ('4-6', '4-6'), ('7-9', '7-9')], max_length=50, null=True, verbose_name='Section'),
        ),
        migrations.AlterField(
            model_name='in_house_drying',
            name='SectionGP_1F',
            field=models.CharField(blank=True, choices=[('', '--Select Section--'), ('1-3', '1-3'), ('4-6', '4-6'), ('7-9', '7-9')], max_length=50, null=True, verbose_name='Section'),
        ),
        migrations.AlterField(
            model_name='in_house_drying',
            name='SectionGP_2F',
            field=models.CharField(blank=True, choices=[('', '--Select Section--'), ('1-3', '1-3'), ('4-6', '4-6'), ('7-9', '7-9')], max_length=50, null=True, verbose_name='Section'),
        ),
        migrations.AlterField(
            model_name='in_house_drying',
            name='SectionGP_FL',
            field=models.CharField(blank=True, choices=[('', '--Select Section--'), ('1-3', '1-3'), ('4-6', '4-6'), ('7-9', '7-9')], max_length=50, null=True, verbose_name='Section'),
        ),
        migrations.AlterField(
            model_name='in_house_drying',
            name='SectionGP_GF',
            field=models.CharField(blank=True, choices=[('', '--Select Section--'), ('1-3', '1-3'), ('4-6', '4-6'), ('7-9', '7-9')], max_length=50, null=True, verbose_name='Section'),
        ),
        migrations.AlterField(
            model_name='in_house_drying',
            name='SectionG_0_1F',
            field=models.CharField(blank=True, choices=[('', '--Select Section--'), ('1-3', '1-3'), ('4-6', '4-6'), ('7-9', '7-9')], max_length=50, null=True, verbose_name='Section'),
        ),
        migrations.AlterField(
            model_name='in_house_drying',
            name='SectionG_0_2F',
            field=models.CharField(blank=True, choices=[('', '--Select Section--'), ('1-3', '1-3'), ('4-6', '4-6'), ('7-9', '7-9')], max_length=50, null=True, verbose_name='Section'),
        ),
        migrations.AlterField(
            model_name='in_house_drying',
            name='SectionG_0_FL',
            field=models.CharField(blank=True, choices=[('', '--Select Section--'), ('1-3', '1-3'), ('4-6', '4-6'), ('7-9', '7-9')], max_length=50, null=True, verbose_name='Section'),
        ),
        migrations.AlterField(
            model_name='in_house_drying',
            name='SectionG_0_GF',
            field=models.CharField(blank=True, choices=[('', '--Select Section--'), ('1-3', '1-3'), ('4-6', '4-6'), ('7-9', '7-9')], max_length=50, null=True, verbose_name='Section'),
        ),
        migrations.AlterField(
            model_name='in_house_drying',
            name='SectionG_1F',
            field=models.CharField(blank=True, choices=[('', '--Select Section--'), ('1-3', '1-3'), ('4-6', '4-6'), ('7-9', '7-9')], max_length=50, null=True, verbose_name='Section'),
        ),
        migrations.AlterField(
            model_name='in_house_drying',
            name='SectionG_2F',
            field=models.CharField(blank=True, choices=[('', '--Select Section--'), ('1-3', '1-3'), ('4-6', '4-6'), ('7-9', '7-9')], max_length=50, null=True, verbose_name='Section'),
        ),
        migrations.AlterField(
            model_name='in_house_drying',
            name='SectionG_FL',
            field=models.CharField(blank=True, choices=[('', '--Select Section--'), ('1-3', '1-3'), ('4-6', '4-6'), ('7-9', '7-9')], max_length=50, null=True, verbose_name='Section'),
        ),
        migrations.AlterField(
            model_name='in_house_drying',
            name='SectionG_GF',
            field=models.CharField(blank=True, choices=[('', '--Select Section--'), ('1-3', '1-3'), ('4-6', '4-6'), ('7-9', '7-9')], max_length=50, null=True, verbose_name='Section'),
        ),
        migrations.AlterField(
            model_name='in_house_drying',
            name='SectionH_0_1F',
            field=models.CharField(blank=True, choices=[('', '--Select Section--'), ('1-3', '1-3'), ('4-6', '4-6'), ('7-9', '7-9')], max_length=50, null=True, verbose_name='Section'),
        ),
        migrations.AlterField(
            model_name='in_house_drying',
            name='SectionH_0_2F',
            field=models.CharField(blank=True, choices=[('', '--Select Section--'), ('1-3', '1-3'), ('4-6', '4-6'), ('7-9', '7-9')], max_length=50, null=True, verbose_name='Section'),
        ),
        migrations.AlterField(
            model_name='in_house_drying',
            name='SectionH_0_FL',
            field=models.CharField(blank=True, choices=[('', '--Select Section--'), ('1-3', '1-3'), ('4-6', '4-6'), ('7-9', '7-9')], max_length=50, null=True, verbose_name='Section'),
        ),
        migrations.AlterField(
            model_name='in_house_drying',
            name='SectionH_0_GF',
            field=models.CharField(blank=True, choices=[('', '--Select Section--'), ('1-3', '1-3'), ('4-6', '4-6'), ('7-9', '7-9')], max_length=50, null=True, verbose_name='Section'),
        ),
        migrations.AlterField(
            model_name='in_house_drying',
            name='SectionH_1F',
            field=models.CharField(blank=True, choices=[('', '--Select Section--'), ('1-3', '1-3'), ('4-6', '4-6'), ('7-9', '7-9')], max_length=50, null=True, verbose_name='Section'),
        ),
        migrations.AlterField(
            model_name='in_house_drying',
            name='SectionH_2F',
            field=models.CharField(blank=True, choices=[('', '--Select Section--'), ('1-3', '1-3'), ('4-6', '4-6'), ('7-9', '7-9')], max_length=50, null=True, verbose_name='Section'),
        ),
        migrations.AlterField(
            model_name='in_house_drying',
            name='SectionH_FL',
            field=models.CharField(blank=True, choices=[('', '--Select Section--'), ('1-3', '1-3'), ('4-6', '4-6'), ('7-9', '7-9')], max_length=50, null=True, verbose_name='Section'),
        ),
        migrations.AlterField(
            model_name='in_house_drying',
            name='SectionH_GF',
            field=models.CharField(blank=True, choices=[('', '--Select Section--'), ('1-3', '1-3'), ('4-6', '4-6'), ('7-9', '7-9')], max_length=50, null=True, verbose_name='Section'),
        ),
        migrations.AlterField(
            model_name='in_house_drying',
            name='SectionM',
            field=models.CharField(blank=True, choices=[('', '--Select Section--'), ('1-3', '1-3'), ('4-6', '4-6'), ('7-9', '7-9')], max_length=50, null=True, verbose_name='Section'),
        ),
        migrations.AlterField(
            model_name='in_house_drying',
            name='SectionM_0_1F',
            field=models.CharField(blank=True, choices=[('', '--Select Section--'), ('1-3', '1-3'), ('4-6', '4-6'), ('7-9', '7-9')], max_length=50, null=True, verbose_name='Section'),
        ),
        migrations.AlterField(
            model_name='in_house_drying',
            name='SectionM_0_2F',
            field=models.CharField(blank=True, choices=[('', '--Select Section--'), ('1-3', '1-3'), ('4-6', '4-6'), ('7-9', '7-9')], max_length=50, null=True, verbose_name='Section'),
        ),
        migrations.AlterField(
            model_name='in_house_drying',
            name='SectionM_0_FL',
            field=models.CharField(blank=True, choices=[('', '--Select Section--'), ('1-3', '1-3'), ('4-6', '4-6'), ('7-9', '7-9')], max_length=50, null=True, verbose_name='Section'),
        ),
        migrations.AlterField(
            model_name='in_house_drying',
            name='SectionM_0_GF',
            field=models.CharField(blank=True, choices=[('', '--Select Section--'), ('1-3', '1-3'), ('4-6', '4-6'), ('7-9', '7-9')], max_length=50, null=True, verbose_name='Section'),
        ),
        migrations.AlterField(
            model_name='in_house_drying',
            name='SectionM_1F',
            field=models.CharField(blank=True, choices=[('', '--Select Section--'), ('1-3', '1-3'), ('4-6', '4-6'), ('7-9', '7-9')], max_length=50, null=True, verbose_name='Section'),
        ),
        migrations.AlterField(
            model_name='in_house_drying',
            name='SectionM_2F',
            field=models.CharField(blank=True, choices=[('', '--Select Section--'), ('1-3', '1-3'), ('4-6', '4-6'), ('7-9', '7-9')], max_length=50, null=True, verbose_name='Section'),
        ),
        migrations.AlterField(
            model_name='in_house_drying',
            name='SectionM_FL',
            field=models.CharField(blank=True, choices=[('', '--Select Section--'), ('1-3', '1-3'), ('4-6', '4-6'), ('7-9', '7-9')], max_length=50, null=True, verbose_name='Section'),
        ),
        migrations.AlterField(
            model_name='in_house_drying',
            name='SectionM_GF',
            field=models.CharField(blank=True, choices=[('', '--Select Section--'), ('1-3', '1-3'), ('4-6', '4-6'), ('7-9', '7-9')], max_length=50, null=True, verbose_name='Section'),
        ),
        migrations.AlterField(
            model_name='in_house_drying',
            name='SectionU_0_1F',
            field=models.CharField(blank=True, choices=[('', '--Select Section--'), ('1-3', '1-3'), ('4-6', '4-6'), ('7-9', '7-9')], max_length=50, null=True, verbose_name='Section'),
        ),
        migrations.AlterField(
            model_name='in_house_drying',
            name='SectionU_0_2F',
            field=models.CharField(blank=True, choices=[('', '--Select Section--'), ('1-3', '1-3'), ('4-6', '4-6'), ('7-9', '7-9')], max_length=50, null=True, verbose_name='Section'),
        ),
        migrations.AlterField(
            model_name='in_house_drying',
            name='SectionU_0_FL',
            field=models.CharField(blank=True, choices=[('', '--Select Section--'), ('1-3', '1-3'), ('4-6', '4-6'), ('7-9', '7-9')], max_length=50, null=True, verbose_name='Section'),
        ),
        migrations.AlterField(
            model_name='in_house_drying',
            name='SectionU_0_GF',
            field=models.CharField(blank=True, choices=[('', '--Select Section--'), ('1-3', '1-3'), ('4-6', '4-6'), ('7-9', '7-9')], max_length=50, null=True, verbose_name='Section'),
        ),
        migrations.AlterField(
            model_name='in_house_drying',
            name='SectionU_1F',
            field=models.CharField(blank=True, choices=[('', '--Select Section--'), ('1-3', '1-3'), ('4-6', '4-6'), ('7-9', '7-9')], max_length=50, null=True, verbose_name='Section'),
        ),
        migrations.AlterField(
            model_name='in_house_drying',
            name='SectionU_2F',
            field=models.CharField(blank=True, choices=[('', '--Select Section--'), ('1-3', '1-3'), ('4-6', '4-6'), ('7-9', '7-9')], max_length=50, null=True, verbose_name='Section'),
        ),
        migrations.AlterField(
            model_name='in_house_drying',
            name='SectionU_FL',
            field=models.CharField(blank=True, choices=[('', '--Select Section--'), ('1-3', '1-3'), ('4-6', '4-6'), ('7-9', '7-9')], max_length=50, null=True, verbose_name='Section'),
        ),
        migrations.AlterField(
            model_name='in_house_drying',
            name='SectionU_GF',
            field=models.CharField(blank=True, choices=[('', '--Select Section--'), ('1-3', '1-3'), ('4-6', '4-6'), ('7-9', '7-9')], max_length=50, null=True, verbose_name='Section'),
        ),
    ]
