# Generated by Django 4.2.1 on 2024-05-06 19:04

from django.db import migrations, models
import gcna_data.models


class Migration(migrations.Migration):

    dependencies = [
        ('gcna_data', '0009_m_shelves_dried_w_shelves_dried_m_shelves_labeltext_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Final_Weight_Inspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(blank=True, null=True)),
                ('Purchase_order', models.CharField(blank=True, max_length=50, null=True)),
                ('product_description', models.CharField(blank=True, max_length=50, null=True)),
                ('Batch_number', models.CharField(blank=True, max_length=50, null=True)),
                ('linkCheck', models.CharField(default=gcna_data.models.shelf_id, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Final_Weight_Inspection_fields',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_number', models.CharField(blank=True, max_length=50, null=True)),
                ('Bag_number', models.CharField(blank=True, max_length=50, null=True)),
                ('weight', models.FloatField(default=0)),
                ('link', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle_Inspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Provider', models.CharField(choices=[('--Select Provider--', '--Select Provider--'), ('GCNA', 'GCNA'), ('Third_Party', 'Third_Party')], default='--Select Provider--', max_length=50, verbose_name='Pakaging Material')),
                ('Provider_cont', models.CharField(blank=True, max_length=50, null=True)),
                ('Vehicle_number', models.CharField(blank=True, max_length=50, null=True)),
                ('Driver_name', models.CharField(blank=True, max_length=50, null=True)),
                ('liscense_check', models.CharField(choices=[('--Select Provider--', '--Select Provider--'), ('GCNA', 'GCNA'), ('Third_Party', 'Third_Party')], default='--Select Provider--', max_length=50)),
                ('insurance_check', models.CharField(choices=[('--Select Provider--', '--Select Provider--'), ('GCNA', 'GCNA'), ('Third_Party', 'Third_Party')], default='--Select Provider--', max_length=50)),
                ('Clean_check', models.CharField(choices=[('--Select Decisiion--', '--Select Decisiion--'), ('Clean', 'Clean'), ('In need of washing', 'In need of washing')], default='--Select Provider--', max_length=50)),
                ('Oil_Spill', models.CharField(choices=[('--Select Decisiion--', '--Select Decisiion--'), ('Yes', 'Yes'), ('No', 'No')], default='--Select Provider--', max_length=50)),
                ('Tyres_fit', models.CharField(choices=[('--Select Decisiion--', '--Select Decisiion--'), ('Yes', 'Yes'), ('No', 'No')], default='--Select Provider--', max_length=50)),
                ('Resisdue_prev_Cargo', models.CharField(choices=[('--Select Decisiion--', '--Select Decisiion--'), ('Yes', 'Yes'), ('No', 'No')], default='--Select Provider--', max_length=50)),
                ('Presence_of_Debris', models.CharField(choices=[('--Select Decisiion--', '--Select Decisiion--'), ('Yes', 'Yes'), ('No', 'No')], default='--Select Provider--', max_length=50)),
                ('Tarpaulin_present', models.CharField(choices=[('--Select Decisiion--', '--Select Decisiion--'), ('Yes', 'Yes'), ('No', 'No')], default='--Select Provider--', max_length=50)),
                ('Cargo_present', models.CharField(choices=[('--Select Decisiion--', '--Select Decisiion--'), ('Mace', 'Mace'), ('Nutmeg', 'Nutmeg')], default='--Select Provider--', max_length=50)),
                ('Condition_of_cargo', models.CharField(choices=[('--Select Decisiion--', '--Select Decisiion--'), ('Dry', 'Dry'), ('Wet', 'Wet')], default='--Select Provider--', max_length=50)),
                ('covered_goods', models.CharField(choices=[('--Select Decisiion--', '--Select Decisiion--'), ('Yes', 'Yes'), ('No', 'No')], default='--Select Provider--', max_length=50)),
                ('vehicle_for_use', models.CharField(choices=[('--Select Decisiion--', '--Select Decisiion--'), ('Yes', 'Yes'), ('No', 'No')], default='--Select Provider--', max_length=50)),
                ('Weather', models.CharField(choices=[('--Select Decisiion--', '--Select Decisiion--'), ('Sunny', 'Sunny'), ('Cloudy', 'Cloudy'), ('Raining', 'Raining')], default='--Select Provider--', max_length=50)),
                ('comments', models.CharField(blank=True, max_length=50, null=True)),
                ('inspected_by', models.CharField(blank=True, max_length=50, null=True)),
                ('verified_by', models.CharField(blank=True, max_length=50, null=True)),
                ('inspected_by_date', models.DateField(blank=True, null=True)),
                ('verified_by_date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
