# Generated by Django 4.2.1 on 2024-05-07 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gcna_data', '0010_final_weight_inspection_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='in_house_drying',
            name='DEFECT',
            field=models.CharField(choices=[('', '--Select Location--'), ('Cracked', 'Cracked'), ('Grow Heads', 'Grow Heads'), ('Lights', 'Lights'), ('Mould', 'Mould')], default='Cracked', max_length=50, verbose_name='Defect'),
        ),
    ]
