# Generated by Django 4.2.1 on 2024-05-07 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gcna_data', '0012_alter_in_house_drying_alert_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='in_house_drying',
            name='MoistureGP_1F',
        ),
        migrations.RemoveField(
            model_name='in_house_drying',
            name='MoistureGP_2F',
        ),
        migrations.RemoveField(
            model_name='in_house_drying',
            name='MoistureGP_FL',
        ),
        migrations.RemoveField(
            model_name='in_house_drying',
            name='MoistureGP_GF',
        ),
        migrations.RemoveField(
            model_name='in_house_drying',
            name='MoistureG_1F',
        ),
        migrations.RemoveField(
            model_name='in_house_drying',
            name='MoistureG_2F',
        ),
        migrations.RemoveField(
            model_name='in_house_drying',
            name='MoistureG_FL',
        ),
        migrations.RemoveField(
            model_name='in_house_drying',
            name='MoistureG_GF',
        ),
        migrations.RemoveField(
            model_name='in_house_drying',
            name='MoistureH_1F',
        ),
        migrations.RemoveField(
            model_name='in_house_drying',
            name='MoistureH_2F',
        ),
        migrations.RemoveField(
            model_name='in_house_drying',
            name='MoistureH_FL',
        ),
        migrations.RemoveField(
            model_name='in_house_drying',
            name='MoistureH_GF',
        ),
        migrations.RemoveField(
            model_name='in_house_drying',
            name='MoistureM_1F',
        ),
        migrations.RemoveField(
            model_name='in_house_drying',
            name='MoistureM_2F',
        ),
        migrations.RemoveField(
            model_name='in_house_drying',
            name='MoistureM_FL',
        ),
        migrations.RemoveField(
            model_name='in_house_drying',
            name='MoistureM_GF',
        ),
        migrations.RemoveField(
            model_name='in_house_drying',
            name='MoistureU_1F',
        ),
        migrations.RemoveField(
            model_name='in_house_drying',
            name='MoistureU_2F',
        ),
        migrations.RemoveField(
            model_name='in_house_drying',
            name='MoistureU_FL',
        ),
        migrations.RemoveField(
            model_name='in_house_drying',
            name='MoistureU_GF',
        ),
        migrations.RemoveField(
            model_name='in_house_drying',
            name='Section',
        ),
        migrations.RemoveField(
            model_name='in_house_drying',
            name='SectionG',
        ),
        migrations.RemoveField(
            model_name='in_house_drying',
            name='SectionGP_0_1F',
        ),
        migrations.RemoveField(
            model_name='in_house_drying',
            name='SectionGP_0_2F',
        ),
        migrations.RemoveField(
            model_name='in_house_drying',
            name='SectionGP_0_FL',
        ),
        migrations.RemoveField(
            model_name='in_house_drying',
            name='SectionGP_0_GF',
        ),
        migrations.RemoveField(
            model_name='in_house_drying',
            name='SectionG_0_1F',
        ),
        migrations.RemoveField(
            model_name='in_house_drying',
            name='SectionG_0_2F',
        ),
        migrations.RemoveField(
            model_name='in_house_drying',
            name='SectionG_0_FL',
        ),
        migrations.RemoveField(
            model_name='in_house_drying',
            name='SectionG_0_GF',
        ),
        migrations.RemoveField(
            model_name='in_house_drying',
            name='SectionH_0_1F',
        ),
        migrations.RemoveField(
            model_name='in_house_drying',
            name='SectionH_0_2F',
        ),
        migrations.RemoveField(
            model_name='in_house_drying',
            name='SectionH_0_FL',
        ),
        migrations.RemoveField(
            model_name='in_house_drying',
            name='SectionH_0_GF',
        ),
        migrations.RemoveField(
            model_name='in_house_drying',
            name='SectionM',
        ),
        migrations.RemoveField(
            model_name='in_house_drying',
            name='SectionM_0_1F',
        ),
        migrations.RemoveField(
            model_name='in_house_drying',
            name='SectionM_0_2F',
        ),
        migrations.RemoveField(
            model_name='in_house_drying',
            name='SectionM_0_FL',
        ),
        migrations.RemoveField(
            model_name='in_house_drying',
            name='SectionM_0_GF',
        ),
        migrations.RemoveField(
            model_name='in_house_drying',
            name='SectionU_0_1F',
        ),
        migrations.RemoveField(
            model_name='in_house_drying',
            name='SectionU_0_2F',
        ),
        migrations.RemoveField(
            model_name='in_house_drying',
            name='SectionU_0_FL',
        ),
        migrations.RemoveField(
            model_name='in_house_drying',
            name='SectionU_0_GF',
        ),
        migrations.RemoveField(
            model_name='in_house_drying',
            name='Shelf',
        ),
        migrations.RemoveField(
            model_name='in_house_drying',
            name='ShelfG',
        ),
        migrations.RemoveField(
            model_name='in_house_drying',
            name='ShelfGP_0_1F',
        ),
        migrations.RemoveField(
            model_name='in_house_drying',
            name='ShelfGP_0_2F',
        ),
        migrations.RemoveField(
            model_name='in_house_drying',
            name='ShelfGP_0_FL',
        ),
        migrations.RemoveField(
            model_name='in_house_drying',
            name='ShelfGP_0_GF',
        ),
        migrations.RemoveField(
            model_name='in_house_drying',
            name='ShelfG_0_1F',
        ),
        migrations.RemoveField(
            model_name='in_house_drying',
            name='ShelfG_0_2F',
        ),
        migrations.RemoveField(
            model_name='in_house_drying',
            name='ShelfG_0_FL',
        ),
        migrations.RemoveField(
            model_name='in_house_drying',
            name='ShelfG_0_GF',
        ),
        migrations.RemoveField(
            model_name='in_house_drying',
            name='ShelfH_0_1F',
        ),
        migrations.RemoveField(
            model_name='in_house_drying',
            name='ShelfH_0_2F',
        ),
        migrations.RemoveField(
            model_name='in_house_drying',
            name='ShelfH_0_FL',
        ),
        migrations.RemoveField(
            model_name='in_house_drying',
            name='ShelfH_0_GF',
        ),
        migrations.RemoveField(
            model_name='in_house_drying',
            name='ShelfM_0_1F',
        ),
        migrations.RemoveField(
            model_name='in_house_drying',
            name='ShelfM_0_2F',
        ),
        migrations.RemoveField(
            model_name='in_house_drying',
            name='ShelfM_0_FL',
        ),
        migrations.RemoveField(
            model_name='in_house_drying',
            name='ShelfM_0_GF',
        ),
        migrations.RemoveField(
            model_name='in_house_drying',
            name='ShelfU_0_1F',
        ),
        migrations.RemoveField(
            model_name='in_house_drying',
            name='ShelfU_0_2F',
        ),
        migrations.RemoveField(
            model_name='in_house_drying',
            name='ShelfU_0_FL',
        ),
        migrations.RemoveField(
            model_name='in_house_drying',
            name='ShelfU_0_GF',
        ),
        migrations.RemoveField(
            model_name='in_house_drying',
            name='Tray',
        ),
        migrations.RemoveField(
            model_name='in_house_drying',
            name='TrayG',
        ),
        migrations.RemoveField(
            model_name='in_house_drying',
            name='TrayGP_0_1F',
        ),
        migrations.RemoveField(
            model_name='in_house_drying',
            name='TrayGP_0_2F',
        ),
        migrations.RemoveField(
            model_name='in_house_drying',
            name='TrayGP_0_FL',
        ),
        migrations.RemoveField(
            model_name='in_house_drying',
            name='TrayGP_0_GF',
        ),
        migrations.RemoveField(
            model_name='in_house_drying',
            name='TrayG_0_1F',
        ),
        migrations.RemoveField(
            model_name='in_house_drying',
            name='TrayG_0_2F',
        ),
        migrations.RemoveField(
            model_name='in_house_drying',
            name='TrayG_0_FL',
        ),
        migrations.RemoveField(
            model_name='in_house_drying',
            name='TrayG_0_GF',
        ),
        migrations.RemoveField(
            model_name='in_house_drying',
            name='TrayH_0_1F',
        ),
        migrations.RemoveField(
            model_name='in_house_drying',
            name='TrayH_0_2F',
        ),
        migrations.RemoveField(
            model_name='in_house_drying',
            name='TrayH_0_FL',
        ),
        migrations.RemoveField(
            model_name='in_house_drying',
            name='TrayH_0_GF',
        ),
        migrations.RemoveField(
            model_name='in_house_drying',
            name='TrayM_0_1F',
        ),
        migrations.RemoveField(
            model_name='in_house_drying',
            name='TrayM_0_2F',
        ),
        migrations.RemoveField(
            model_name='in_house_drying',
            name='TrayM_0_FL',
        ),
        migrations.RemoveField(
            model_name='in_house_drying',
            name='TrayM_0_GF',
        ),
        migrations.RemoveField(
            model_name='in_house_drying',
            name='TrayU_0_1F',
        ),
        migrations.RemoveField(
            model_name='in_house_drying',
            name='TrayU_0_2F',
        ),
        migrations.RemoveField(
            model_name='in_house_drying',
            name='TrayU_0_FL',
        ),
        migrations.RemoveField(
            model_name='in_house_drying',
            name='TrayU_0_GF',
        ),
        migrations.AlterField(
            model_name='in_house_drying',
            name='ALERT',
            field=models.CharField(blank=True, choices=[('', 'Send Alert?'), ('Yes', 'Yes'), ('No', 'No')], max_length=50, null=True, verbose_name='Alert'),
        ),
        migrations.AlterField(
            model_name='in_house_drying',
            name='DEFECT',
            field=models.CharField(choices=[('', '--Select Location--'), ('Cracked', 'Cracked'), ('Grow Heads', 'Grow Heads'), ('Lights', 'Lights'), ('Mould', 'Mould')], default='A', max_length=50, verbose_name='Defect'),
        ),
        migrations.AlterField(
            model_name='in_house_drying',
            name='SectionGP_1F',
            field=models.CharField(blank=True, choices=[('', '--Select Section--'), ('1-3', '1-3'), ('4-6', '4-6'), ('7-9', '7-9')], max_length=50, null=True, verbose_name='Section'),
        ),
        migrations.AlterField(
            model_name='in_house_drying',
            name='SectionGP_2F',
            field=models.CharField(blank=True, choices=[('', '--Select Section--'), ('1-3', '1-3'), ('4-6', '4-6'), ('7-9', '7-9')], max_length=50, null=True, verbose_name='Section'),
        ),
        migrations.AlterField(
            model_name='in_house_drying',
            name='SectionGP_FL',
            field=models.CharField(blank=True, choices=[('', '--Select Section--'), ('1-3', '1-3'), ('4-6', '4-6'), ('7-9', '7-9')], max_length=50, null=True, verbose_name='Section'),
        ),
        migrations.AlterField(
            model_name='in_house_drying',
            name='SectionGP_GF',
            field=models.CharField(blank=True, choices=[('', '--Select Section--'), ('1-3', '1-3'), ('4-6', '4-6'), ('7-9', '7-9')], max_length=50, null=True, verbose_name='Section'),
        ),
        migrations.AlterField(
            model_name='in_house_drying',
            name='SectionG_1F',
            field=models.CharField(blank=True, choices=[('', '--Select Section--'), ('1-3', '1-3'), ('4-6', '4-6'), ('7-9', '7-9')], max_length=50, null=True, verbose_name='Section'),
        ),
        migrations.AlterField(
            model_name='in_house_drying',
            name='SectionG_2F',
            field=models.CharField(blank=True, choices=[('', '--Select Section--'), ('1-3', '1-3'), ('4-6', '4-6'), ('7-9', '7-9')], max_length=50, null=True, verbose_name='Section'),
        ),
        migrations.AlterField(
            model_name='in_house_drying',
            name='SectionG_FL',
            field=models.CharField(blank=True, choices=[('', '--Select Section--'), ('1-3', '1-3'), ('4-6', '4-6'), ('7-9', '7-9')], max_length=50, null=True, verbose_name='Section'),
        ),
        migrations.AlterField(
            model_name='in_house_drying',
            name='SectionG_GF',
            field=models.CharField(blank=True, choices=[('', '--Select Section--'), ('1-3', '1-3'), ('4-6', '4-6'), ('7-9', '7-9')], max_length=50, null=True, verbose_name='Section'),
        ),
        migrations.AlterField(
            model_name='in_house_drying',
            name='SectionH_1F',
            field=models.CharField(blank=True, choices=[('', '--Select Section--'), ('1-3', '1-3'), ('4-6', '4-6'), ('7-9', '7-9')], max_length=50, null=True, verbose_name='Section'),
        ),
        migrations.AlterField(
            model_name='in_house_drying',
            name='SectionH_2F',
            field=models.CharField(blank=True, choices=[('', '--Select Section--'), ('1-3', '1-3'), ('4-6', '4-6'), ('7-9', '7-9')], max_length=50, null=True, verbose_name='Section'),
        ),
        migrations.AlterField(
            model_name='in_house_drying',
            name='SectionH_FL',
            field=models.CharField(blank=True, choices=[('', '--Select Section--'), ('1-3', '1-3'), ('4-6', '4-6'), ('7-9', '7-9')], max_length=50, null=True, verbose_name='Section'),
        ),
        migrations.AlterField(
            model_name='in_house_drying',
            name='SectionH_GF',
            field=models.CharField(blank=True, choices=[('', '--Select Section--'), ('1-3', '1-3'), ('4-6', '4-6'), ('7-9', '7-9')], max_length=50, null=True, verbose_name='Section'),
        ),
        migrations.AlterField(
            model_name='in_house_drying',
            name='SectionM_1F',
            field=models.CharField(blank=True, choices=[('', '--Select Section--'), ('1-3', '1-3'), ('4-6', '4-6'), ('7-9', '7-9')], max_length=50, null=True, verbose_name='Section'),
        ),
        migrations.AlterField(
            model_name='in_house_drying',
            name='SectionM_2F',
            field=models.CharField(blank=True, choices=[('', '--Select Section--'), ('1-3', '1-3'), ('4-6', '4-6'), ('7-9', '7-9')], max_length=50, null=True, verbose_name='Section'),
        ),
        migrations.AlterField(
            model_name='in_house_drying',
            name='SectionM_FL',
            field=models.CharField(blank=True, choices=[('', '--Select Section--'), ('1-3', '1-3'), ('4-6', '4-6'), ('7-9', '7-9')], max_length=50, null=True, verbose_name='Section'),
        ),
        migrations.AlterField(
            model_name='in_house_drying',
            name='SectionM_GF',
            field=models.CharField(blank=True, choices=[('', '--Select Section--'), ('1-3', '1-3'), ('4-6', '4-6'), ('7-9', '7-9')], max_length=50, null=True, verbose_name='Section'),
        ),
        migrations.AlterField(
            model_name='in_house_drying',
            name='SectionU_1F',
            field=models.CharField(blank=True, choices=[('', '--Select Section--'), ('1-3', '1-3'), ('4-6', '4-6'), ('7-9', '7-9')], max_length=50, null=True, verbose_name='Section'),
        ),
        migrations.AlterField(
            model_name='in_house_drying',
            name='SectionU_2F',
            field=models.CharField(blank=True, choices=[('', '--Select Section--'), ('1-3', '1-3'), ('4-6', '4-6'), ('7-9', '7-9')], max_length=50, null=True, verbose_name='Section'),
        ),
        migrations.AlterField(
            model_name='in_house_drying',
            name='SectionU_FL',
            field=models.CharField(blank=True, choices=[('', '--Select Section--'), ('1-3', '1-3'), ('4-6', '4-6'), ('7-9', '7-9')], max_length=50, null=True, verbose_name='Section'),
        ),
        migrations.AlterField(
            model_name='in_house_drying',
            name='SectionU_GF',
            field=models.CharField(blank=True, choices=[('', '--Select Section--'), ('1-3', '1-3'), ('4-6', '4-6'), ('7-9', '7-9')], max_length=50, null=True, verbose_name='Section'),
        ),
        migrations.AlterField(
            model_name='in_house_drying',
            name='ShelfGP_1F',
            field=models.CharField(blank=True, choices=[('', '--Select shelf--'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G'), ('H', 'H'), ('I', 'I'), ('J', 'J'), ('K', 'K'), ('L', 'L')], max_length=50, null=True, verbose_name='Shelf'),
        ),
        migrations.AlterField(
            model_name='in_house_drying',
            name='ShelfGP_2F',
            field=models.CharField(blank=True, choices=[('', '--Select shelf--'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G'), ('H', 'H'), ('I', 'I'), ('J', 'J'), ('K', 'K'), ('L', 'L')], max_length=50, null=True, verbose_name='Shelf'),
        ),
        migrations.AlterField(
            model_name='in_house_drying',
            name='ShelfGP_FL',
            field=models.CharField(blank=True, choices=[('', '--Select shelf--'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G'), ('H', 'H'), ('I', 'I'), ('J', 'J'), ('K', 'K'), ('L', 'L')], max_length=50, null=True, verbose_name='Shelf'),
        ),
        migrations.AlterField(
            model_name='in_house_drying',
            name='ShelfGP_GF',
            field=models.CharField(blank=True, choices=[('', '--Select shelf--'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G'), ('H', 'H'), ('I', 'I'), ('J', 'J'), ('K', 'K'), ('L', 'L')], max_length=50, null=True, verbose_name='Shelf'),
        ),
        migrations.AlterField(
            model_name='in_house_drying',
            name='ShelfG_1F',
            field=models.CharField(blank=True, choices=[('', '--Select shelf--'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G'), ('H', 'H'), ('I', 'I'), ('J', 'J'), ('K', 'K'), ('L', 'L')], max_length=50, null=True, verbose_name='Shelf'),
        ),
        migrations.AlterField(
            model_name='in_house_drying',
            name='ShelfG_2F',
            field=models.CharField(blank=True, choices=[('', '--Select shelf--'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G'), ('H', 'H'), ('I', 'I'), ('J', 'J'), ('K', 'K'), ('L', 'L')], max_length=50, null=True, verbose_name='Shelf'),
        ),
        migrations.AlterField(
            model_name='in_house_drying',
            name='ShelfG_FL',
            field=models.CharField(blank=True, choices=[('', '--Select shelf--'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G'), ('H', 'H'), ('I', 'I'), ('J', 'J'), ('K', 'K'), ('L', 'L')], max_length=50, null=True, verbose_name='Shelf'),
        ),
        migrations.AlterField(
            model_name='in_house_drying',
            name='ShelfG_GF',
            field=models.CharField(blank=True, choices=[('', '--Select shelf--'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G'), ('H', 'H'), ('I', 'I'), ('J', 'J'), ('K', 'K'), ('L', 'L')], max_length=50, null=True, verbose_name='Shelf'),
        ),
        migrations.AlterField(
            model_name='in_house_drying',
            name='ShelfH_1F',
            field=models.CharField(blank=True, choices=[('', '--Select shelf--'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G'), ('H', 'H'), ('I', 'I'), ('J', 'J'), ('K', 'K'), ('L', 'L')], max_length=50, null=True, verbose_name='Shelf'),
        ),
        migrations.AlterField(
            model_name='in_house_drying',
            name='ShelfH_2F',
            field=models.CharField(blank=True, choices=[('', '--Select shelf--'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G'), ('H', 'H'), ('I', 'I'), ('J', 'J'), ('K', 'K'), ('L', 'L')], max_length=50, null=True, verbose_name='Shelf'),
        ),
        migrations.AlterField(
            model_name='in_house_drying',
            name='ShelfH_FL',
            field=models.CharField(blank=True, choices=[('', '--Select shelf--'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G'), ('H', 'H'), ('I', 'I'), ('J', 'J'), ('K', 'K'), ('L', 'L')], max_length=50, null=True, verbose_name='Shelf'),
        ),
        migrations.AlterField(
            model_name='in_house_drying',
            name='ShelfH_GF',
            field=models.CharField(blank=True, choices=[('', '--Select shelf--'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G'), ('H', 'H'), ('I', 'I'), ('J', 'J'), ('K', 'K'), ('L', 'L')], max_length=50, null=True, verbose_name='Shelf'),
        ),
        migrations.AlterField(
            model_name='in_house_drying',
            name='ShelfM_1F',
            field=models.CharField(blank=True, choices=[('', '--Select shelf--'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G'), ('H', 'H'), ('I', 'I'), ('J', 'J'), ('K', 'K'), ('L', 'L')], max_length=50, null=True, verbose_name='Shelf'),
        ),
        migrations.AlterField(
            model_name='in_house_drying',
            name='ShelfM_2F',
            field=models.CharField(blank=True, choices=[('', '--Select shelf--'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G'), ('H', 'H'), ('I', 'I'), ('J', 'J'), ('K', 'K'), ('L', 'L')], max_length=50, null=True, verbose_name='Shelf'),
        ),
        migrations.AlterField(
            model_name='in_house_drying',
            name='ShelfM_FL',
            field=models.CharField(blank=True, choices=[('', '--Select shelf--'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G'), ('H', 'H'), ('I', 'I'), ('J', 'J'), ('K', 'K'), ('L', 'L')], max_length=50, null=True, verbose_name='Shelf'),
        ),
        migrations.AlterField(
            model_name='in_house_drying',
            name='ShelfM_GF',
            field=models.CharField(blank=True, choices=[('', '--Select shelf--'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G'), ('H', 'H'), ('I', 'I'), ('J', 'J'), ('K', 'K'), ('L', 'L')], max_length=50, null=True, verbose_name='Shelf'),
        ),
        migrations.AlterField(
            model_name='in_house_drying',
            name='ShelfU_1F',
            field=models.CharField(blank=True, choices=[('', '--Select shelf--'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G'), ('H', 'H'), ('I', 'I'), ('J', 'J'), ('K', 'K'), ('L', 'L')], max_length=50, null=True, verbose_name='Shelf'),
        ),
        migrations.AlterField(
            model_name='in_house_drying',
            name='ShelfU_2F',
            field=models.CharField(blank=True, choices=[('', '--Select shelf--'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G'), ('H', 'H'), ('I', 'I'), ('J', 'J'), ('K', 'K'), ('L', 'L')], max_length=50, null=True, verbose_name='Shelf'),
        ),
        migrations.AlterField(
            model_name='in_house_drying',
            name='ShelfU_FL',
            field=models.CharField(blank=True, choices=[('', '--Select shelf--'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G'), ('H', 'H'), ('I', 'I'), ('J', 'J'), ('K', 'K'), ('L', 'L')], max_length=50, null=True, verbose_name='Shelf'),
        ),
        migrations.AlterField(
            model_name='in_house_drying',
            name='ShelfU_GF',
            field=models.CharField(blank=True, choices=[('', '--Select shelf--'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G'), ('H', 'H'), ('I', 'I'), ('J', 'J'), ('K', 'K'), ('L', 'L')], max_length=50, null=True, verbose_name='Shelf'),
        ),
        migrations.AlterField(
            model_name='in_house_drying',
            name='TrayGP_1F',
            field=models.CharField(blank=True, choices=[('', '--Select Tray--'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], max_length=50, null=True, verbose_name='Tray'),
        ),
        migrations.AlterField(
            model_name='in_house_drying',
            name='TrayGP_2F',
            field=models.CharField(blank=True, choices=[('', '--Select Tray--'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], max_length=50, null=True, verbose_name='Tray'),
        ),
        migrations.AlterField(
            model_name='in_house_drying',
            name='TrayGP_FL',
            field=models.CharField(blank=True, choices=[('', '--Select Tray--'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], max_length=50, null=True, verbose_name='Tray'),
        ),
        migrations.AlterField(
            model_name='in_house_drying',
            name='TrayGP_GF',
            field=models.CharField(blank=True, choices=[('', '--Select Tray--'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], max_length=50, null=True, verbose_name='Tray'),
        ),
        migrations.AlterField(
            model_name='in_house_drying',
            name='TrayG_1F',
            field=models.CharField(blank=True, choices=[('', '--Select Tray--'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], max_length=50, null=True, verbose_name='Tray'),
        ),
        migrations.AlterField(
            model_name='in_house_drying',
            name='TrayG_2F',
            field=models.CharField(blank=True, choices=[('', '--Select Tray--'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], max_length=50, null=True, verbose_name='Tray'),
        ),
        migrations.AlterField(
            model_name='in_house_drying',
            name='TrayG_FL',
            field=models.CharField(blank=True, choices=[('', '--Select Tray--'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], max_length=50, null=True, verbose_name='Tray'),
        ),
        migrations.AlterField(
            model_name='in_house_drying',
            name='TrayG_GF',
            field=models.CharField(blank=True, choices=[('', '--Select Tray--'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], max_length=50, null=True, verbose_name='Tray'),
        ),
        migrations.AlterField(
            model_name='in_house_drying',
            name='TrayH_1F',
            field=models.CharField(blank=True, choices=[('', '--Select Tray--'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], max_length=50, null=True, verbose_name='Tray'),
        ),
        migrations.AlterField(
            model_name='in_house_drying',
            name='TrayH_2F',
            field=models.CharField(blank=True, choices=[('', '--Select Tray--'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], max_length=50, null=True, verbose_name='Tray'),
        ),
        migrations.AlterField(
            model_name='in_house_drying',
            name='TrayH_FL',
            field=models.CharField(blank=True, choices=[('', '--Select Tray--'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], max_length=50, null=True, verbose_name='Tray'),
        ),
        migrations.AlterField(
            model_name='in_house_drying',
            name='TrayH_GF',
            field=models.CharField(blank=True, choices=[('', '--Select Tray--'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], max_length=50, null=True, verbose_name='Tray'),
        ),
        migrations.AlterField(
            model_name='in_house_drying',
            name='TrayM_1F',
            field=models.CharField(blank=True, choices=[('', '--Select Tray--'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], max_length=50, null=True, verbose_name='Tray'),
        ),
        migrations.AlterField(
            model_name='in_house_drying',
            name='TrayM_2F',
            field=models.CharField(blank=True, choices=[('', '--Select Tray--'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], max_length=50, null=True, verbose_name='Tray'),
        ),
        migrations.AlterField(
            model_name='in_house_drying',
            name='TrayM_FL',
            field=models.CharField(blank=True, choices=[('', '--Select Tray--'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], max_length=50, null=True, verbose_name='Tray'),
        ),
        migrations.AlterField(
            model_name='in_house_drying',
            name='TrayM_GF',
            field=models.CharField(blank=True, choices=[('', '--Select Tray--'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], max_length=50, null=True, verbose_name='Tray'),
        ),
        migrations.AlterField(
            model_name='in_house_drying',
            name='TrayU_1F',
            field=models.CharField(blank=True, choices=[('', '--Select Tray--'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], max_length=50, null=True, verbose_name='Tray'),
        ),
        migrations.AlterField(
            model_name='in_house_drying',
            name='TrayU_2F',
            field=models.CharField(blank=True, choices=[('', '--Select Tray--'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], max_length=50, null=True, verbose_name='Tray'),
        ),
        migrations.AlterField(
            model_name='in_house_drying',
            name='TrayU_FL',
            field=models.CharField(blank=True, choices=[('', '--Select Tray--'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], max_length=50, null=True, verbose_name='Tray'),
        ),
        migrations.AlterField(
            model_name='in_house_drying',
            name='TrayU_GF',
            field=models.CharField(blank=True, choices=[('', '--Select Tray--'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], max_length=50, null=True, verbose_name='Tray'),
        ),
        migrations.AlterField(
            model_name='in_house_drying',
            name='WeightGP_1F',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Section'),
        ),
        migrations.AlterField(
            model_name='in_house_drying',
            name='WeightGP_2F',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Section'),
        ),
        migrations.AlterField(
            model_name='in_house_drying',
            name='WeightGP_FL',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Section'),
        ),
        migrations.AlterField(
            model_name='in_house_drying',
            name='WeightGP_GF',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Section'),
        ),
        migrations.AlterField(
            model_name='in_house_drying',
            name='WeightG_1F',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Section'),
        ),
        migrations.AlterField(
            model_name='in_house_drying',
            name='WeightG_2F',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Section'),
        ),
        migrations.AlterField(
            model_name='in_house_drying',
            name='WeightG_FL',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Section'),
        ),
        migrations.AlterField(
            model_name='in_house_drying',
            name='WeightG_GF',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Section'),
        ),
        migrations.AlterField(
            model_name='in_house_drying',
            name='WeightH_1F',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Section'),
        ),
        migrations.AlterField(
            model_name='in_house_drying',
            name='WeightH_2F',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Section'),
        ),
        migrations.AlterField(
            model_name='in_house_drying',
            name='WeightH_FL',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Section'),
        ),
        migrations.AlterField(
            model_name='in_house_drying',
            name='WeightH_GF',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Section'),
        ),
        migrations.AlterField(
            model_name='in_house_drying',
            name='WeightM_1F',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Section'),
        ),
        migrations.AlterField(
            model_name='in_house_drying',
            name='WeightM_2F',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Section'),
        ),
        migrations.AlterField(
            model_name='in_house_drying',
            name='WeightM_FL',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Section'),
        ),
        migrations.AlterField(
            model_name='in_house_drying',
            name='WeightM_GF',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Section'),
        ),
        migrations.AlterField(
            model_name='in_house_drying',
            name='WeightU_1F',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Section'),
        ),
        migrations.AlterField(
            model_name='in_house_drying',
            name='WeightU_2F',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Section'),
        ),
        migrations.AlterField(
            model_name='in_house_drying',
            name='WeightU_FL',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Section'),
        ),
        migrations.AlterField(
            model_name='in_house_drying',
            name='WeightU_GF',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Section'),
        ),
    ]
