# Generated by Django 4.2.1 on 2024-05-07 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gcna_data', '0013_remove_in_house_drying_moisturegp_1f_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispatch_of_dried_nutmeg',
            name='Control_number',
            field=models.CharField(default=0, max_length=50, verbose_name='Control Number'),
        ),
        migrations.AlterField(
            model_name='dispatch_of_dried_nutmeg',
            name='FINAL_MOISTURE_CONTENT',
            field=models.CharField(default=0, max_length=50, verbose_name='Final moisture content'),
        ),
        migrations.AlterField(
            model_name='in_house_drying',
            name='NUM_OF_BAGS',
            field=models.CharField(default=0, max_length=50, verbose_name='Number of Bags'),
        ),
        migrations.AlterField(
            model_name='in_house_drying',
            name='TOTAL_LBS_NUTMEG_BOUGHT',
            field=models.CharField(default=0, max_length=50, null=True, verbose_name='Total lbs of nutmeg bought'),
        ),
        migrations.AlterField(
            model_name='in_house_drying',
            name='TOTAL_NUM_OF_FARMERS',
            field=models.CharField(default=0, max_length=50, verbose_name='Total Numbers of Farmers'),
        ),
    ]
