# Generated by Django 4.2.1 on 2024-05-08 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gcna_data', '0014_alter_dispatch_of_dried_nutmeg_control_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='m_shelves',
            name='Batchcode',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='m_shelves_dried',
            name='Batchcode',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='shelves',
            name='Batchcode',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='w_shelves',
            name='Batchcode',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='w_shelves_dried',
            name='Batchcode',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
