# Generated by Django 4.2.1 on 2024-05-08 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gcna_data', '0015_m_shelves_batchcode_m_shelves_dried_batchcode_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shelves',
            name='Batchcode',
        ),
        migrations.AddField(
            model_name='m_shelves',
            name='Week',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='m_shelves_dried',
            name='Week',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='w_shelves',
            name='Week',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='w_shelves_dried',
            name='Week',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
