# Generated by Django 4.2.1 on 2024-05-10 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gcna_data', '0016_remove_shelves_batchcode_m_shelves_week_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle_inspection',
            name='Provider_cont',
        ),
        migrations.AddField(
            model_name='dispatch_of_dried_nutmeg',
            name='Vehicle_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='dispatch_of_green_nutmeg',
            name='BATCH_CODES',
            field=models.CharField(max_length=150, null=True, verbose_name='Batch Codes'),
        ),
        migrations.AddField(
            model_name='floation_summary',
            name='BATCH_CODES',
            field=models.CharField(max_length=150, null=True, verbose_name='Batch Codes'),
        ),
        migrations.AlterField(
            model_name='vehicle_inspection',
            name='insurance_check',
            field=models.CharField(choices=[('--Select Decisiion--', '--Select Decisiion--'), ('Yes', 'Yes'), ('No', 'No')], default='--Select Decisiion--', max_length=50),
        ),
        migrations.AlterField(
            model_name='vehicle_inspection',
            name='liscense_check',
            field=models.CharField(choices=[('--Select Decisiion--', '--Select Decisiion--'), ('Yes', 'Yes'), ('No', 'No')], default='--Select Decisiion--', max_length=50),
        ),
    ]
