# Generated by Django 4.2.1 on 2024-05-15 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gcna_data', '0018_dispatch_of_dried_nutmeg_batch_codes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dispatch_Of_Dried_Nutmeg_Rec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('To_Station', models.CharField(blank=True, max_length=50, null=True)),
                ('From_Station', models.CharField(blank=True, max_length=50, null=True)),
                ('BatchCode', models.CharField(blank=True, max_length=50, null=True)),
                ('Vehicle_number', models.CharField(blank=True, max_length=50, null=True)),
                ('Delivery_advice_num', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dispatch_Of_Green_Nutmeg_Rec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('To_Station', models.CharField(blank=True, max_length=50, null=True)),
                ('From_Station', models.CharField(blank=True, max_length=50, null=True)),
                ('BatchCode', models.CharField(blank=True, max_length=50, null=True)),
                ('Vehicle_number', models.CharField(blank=True, max_length=50, null=True)),
                ('Delivery_advice_num', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='m_shelves',
            name='DATE',
            field=models.DateField(null=True, verbose_name='Current Date'),
        ),
        migrations.AddField(
            model_name='m_shelves_dried',
            name='DATE',
            field=models.DateField(null=True, verbose_name='Current Date'),
        ),
        migrations.AddField(
            model_name='w_shelves',
            name='DATE',
            field=models.DateField(null=True, verbose_name='Current Date'),
        ),
        migrations.AddField(
            model_name='w_shelves_dried',
            name='DATE',
            field=models.DateField(null=True, verbose_name='Current Date'),
        ),
        migrations.AlterField(
            model_name='in_house_drying',
            name='SectionGP_1F',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Section'),
        ),
        migrations.AlterField(
            model_name='in_house_drying',
            name='SectionGP_2F',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Section'),
        ),
        migrations.AlterField(
            model_name='in_house_drying',
            name='SectionGP_FL',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Section'),
        ),
        migrations.AlterField(
            model_name='in_house_drying',
            name='SectionGP_GF',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Section'),
        ),
        migrations.AlterField(
            model_name='in_house_drying',
            name='SectionG_1F',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Section'),
        ),
        migrations.AlterField(
            model_name='in_house_drying',
            name='SectionG_2F',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Section'),
        ),
        migrations.AlterField(
            model_name='in_house_drying',
            name='SectionG_FL',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Section'),
        ),
        migrations.AlterField(
            model_name='in_house_drying',
            name='SectionG_GF',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Section'),
        ),
        migrations.AlterField(
            model_name='in_house_drying',
            name='SectionH_1F',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Section'),
        ),
        migrations.AlterField(
            model_name='in_house_drying',
            name='SectionH_2F',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Section'),
        ),
        migrations.AlterField(
            model_name='in_house_drying',
            name='SectionH_FL',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Section'),
        ),
        migrations.AlterField(
            model_name='in_house_drying',
            name='SectionH_GF',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Section'),
        ),
        migrations.AlterField(
            model_name='in_house_drying',
            name='SectionM_1F',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Section'),
        ),
        migrations.AlterField(
            model_name='in_house_drying',
            name='SectionM_2F',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Section'),
        ),
        migrations.AlterField(
            model_name='in_house_drying',
            name='SectionM_FL',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Section'),
        ),
        migrations.AlterField(
            model_name='in_house_drying',
            name='SectionM_GF',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Section'),
        ),
        migrations.AlterField(
            model_name='in_house_drying',
            name='SectionU_1F',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Section'),
        ),
        migrations.AlterField(
            model_name='in_house_drying',
            name='SectionU_2F',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Section'),
        ),
        migrations.AlterField(
            model_name='in_house_drying',
            name='SectionU_FL',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Section'),
        ),
        migrations.AlterField(
            model_name='in_house_drying',
            name='SectionU_GF',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Section'),
        ),
    ]
