# Generated by Django 4.2.1 on 2024-05-24 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gcna_data', '0023_remove_mace_purchase_delivery_advice_num_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mace_Dispatched_Rec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('STATION', models.CharField(max_length=50, null=True, verbose_name='Station')),
                ('BATCH_CODE_M1', models.CharField(max_length=50, null=True, verbose_name='Place of Purchase ')),
                ('BATCH_CODE_M2', models.CharField(max_length=50, null=True, verbose_name='Place of Purchase ')),
                ('BATCH_CODE_M3', models.CharField(max_length=50, null=True, verbose_name='Place of Purchase ')),
                ('Vehicle_number', models.CharField(blank=True, max_length=50, null=True)),
                ('Delivery_advice_num', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='mace_purchase',
            old_name='BATCH_CODE',
            new_name='BATCH_CODE_M1',
        ),
        migrations.AddField(
            model_name='mace_dispatched',
            name='BATCH_CODE_M1',
            field=models.CharField(max_length=50, null=True, verbose_name='Place of Purchase '),
        ),
        migrations.AddField(
            model_name='mace_dispatched',
            name='BATCH_CODE_M2',
            field=models.CharField(max_length=50, null=True, verbose_name='Place of Purchase '),
        ),
        migrations.AddField(
            model_name='mace_dispatched',
            name='BATCH_CODE_M3',
            field=models.CharField(max_length=50, null=True, verbose_name='Place of Purchase '),
        ),
        migrations.AddField(
            model_name='mace_purchase',
            name='BATCH_CODE_M2',
            field=models.CharField(max_length=50, null=True, verbose_name='Place of Purchase '),
        ),
        migrations.AddField(
            model_name='mace_purchase',
            name='BATCH_CODE_M3',
            field=models.CharField(max_length=50, null=True, verbose_name='Place of Purchase '),
        ),
    ]
