# Generated by Django 4.2.1 on 2024-06-11 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gcna_data', '0024_mace_dispatched_rec_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cracking_Extraction_Summary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Worker_ID_No', models.CharField(blank=True, max_length=50, null=True)),
                ('Worker_ID_Name', models.CharField(blank=True, max_length=50, null=True)),
                ('DATE_CREATED', models.DateField(null=True, verbose_name='Date of Sampling')),
                ('STATION', models.CharField(choices=[('', '--Select Location--'), ('H', 'Beaulieu'), ('M', 'Gouyave'), ('G', 'Grenville')], max_length=50, null=True, verbose_name='Station')),
                ('DATE_OF_CRACKING', models.DateField(null=True, verbose_name='Date of cracking')),
                ('WAREHOUSE_RECEIPT_NUMBERS', models.CharField(max_length=50, null=True, verbose_name='Warehouse Reciept Number')),
                ('NUM_OF_BAGS', models.IntegerField(default=0, verbose_name='Number of Bags')),
                ('LBS_OF_NUTMEGS_CRACKED', models.IntegerField(default=0, verbose_name='Lbs of Nutmegs cracked')),
                ('Delivery_Advice_Num', models.CharField(max_length=50, null=True, verbose_name='Number of Bags')),
                ('Control_Num', models.CharField(max_length=50, null=True, verbose_name='Number of Bags')),
                ('BatchCodes', models.CharField(max_length=50, null=True, verbose_name='Number of Bags')),
                ('num_pieces', models.CharField(max_length=50, null=True)),
                ('fragments', models.CharField(max_length=50, null=True)),
                ('regular_nutmeg', models.CharField(max_length=50, null=True)),
                ('escape_nutmeg', models.CharField(max_length=50, null=True)),
                ('num_floaters', models.CharField(max_length=50, null=True)),
                ('lbs_floated', models.CharField(max_length=50, null=True)),
                ('date', models.CharField(max_length=50, null=True)),
                ('lbs_lights', models.CharField(max_length=50, null=True)),
                ('lbs_heavies', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='cracking_summary',
            name='BatchCodes',
            field=models.CharField(max_length=50, null=True, verbose_name='Number of Bags'),
        ),
        migrations.AddField(
            model_name='cracking_summary',
            name='date',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='cracking_summary',
            name='escape_nutmeg',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='cracking_summary',
            name='fragments',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='cracking_summary',
            name='num_pieces',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='cracking_summary',
            name='regular_nutmeg',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='dispatch_of_dried_nutmeg',
            name='Num_Bags',
            field=models.CharField(max_length=50, null=True, verbose_name='Corresponding Delivery Advice'),
        ),
        migrations.AddField(
            model_name='dispatch_of_dried_nutmeg',
            name='Product',
            field=models.CharField(max_length=50, null=True, verbose_name='Corresponding Delivery Advice'),
        ),
        migrations.AddField(
            model_name='dispatch_of_dried_nutmeg',
            name='STATION_recieved',
            field=models.CharField(choices=[('', '--Select Location--'), ('G', 'Grenville'), ('H', 'Hermitage'), ('M', 'Marli'), ('U', 'Union'), ('GP', 'Gouyave')], max_length=50, null=True, verbose_name='Station'),
        ),
        migrations.AddField(
            model_name='dispatch_of_dried_nutmeg',
            name='Weight',
            field=models.CharField(max_length=50, null=True, verbose_name='Corresponding Delivery Advice'),
        ),
        migrations.AddField(
            model_name='dispatch_of_dried_nutmeg_rec',
            name='Date',
            field=models.DateField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='dispatch_of_dried_nutmeg_rec',
            name='Num_Bags',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='dispatch_of_dried_nutmeg_rec',
            name='Product',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='dispatch_of_dried_nutmeg_rec',
            name='Station_rec',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='dispatch_of_dried_nutmeg_rec',
            name='WAREHOUSE_RECEIPT_NUMBER',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='dispatch_of_dried_nutmeg_rec',
            name='Weight',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='dispatch_of_dried_nutmeg_rec',
            name='conf_Num_Bags',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='dispatch_of_dried_nutmeg_rec',
            name='conf_Product',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='dispatch_of_dried_nutmeg_rec',
            name='conf_Weight',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='dispatch_of_green_nutmeg_rec',
            name='Date',
            field=models.DateField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='dispatch_of_green_nutmeg_rec',
            name='Num_Bags',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='dispatch_of_green_nutmeg_rec',
            name='Product',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='dispatch_of_green_nutmeg_rec',
            name='Station_rec',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='dispatch_of_green_nutmeg_rec',
            name='Weight',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='dispatch_of_green_nutmeg_rec',
            name='conf_Num_Bags',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='dispatch_of_green_nutmeg_rec',
            name='conf_Product',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='dispatch_of_green_nutmeg_rec',
            name='conf_Weight',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='mace_dispatched_rec',
            name='Date',
            field=models.DateField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='mace_dispatched_rec',
            name='Num_Bags',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='mace_dispatched_rec',
            name='Product',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='mace_dispatched_rec',
            name='Station_rec',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='mace_dispatched_rec',
            name='Weight',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='mace_dispatched_rec',
            name='conf_Num_Bags',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='mace_dispatched_rec',
            name='conf_Product',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='mace_dispatched_rec',
            name='conf_Weight',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='cracking_summary',
            name='Control_Num',
            field=models.CharField(max_length=50, null=True, verbose_name='Number of Bags'),
        ),
        migrations.AlterField(
            model_name='cracking_summary',
            name='Delivery_Advice_Num',
            field=models.CharField(max_length=50, null=True, verbose_name='Number of Bags'),
        ),
        migrations.AlterField(
            model_name='mace_dispatched_rec',
            name='STATION',
            field=models.CharField(choices=[('', '--Select Location--'), ('G', 'Grenville'), ('H', 'Hermitage'), ('M', 'Marli'), ('U', 'Union'), ('GP', 'Gouyave')], max_length=50, null=True, verbose_name='Station'),
        ),
    ]
